name: Build-Test
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-test:
    # Name the Job
    name: Build test
    # Set the type of machine to run on
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    container: ros:noetic
    # Only run when merging to main.
    # if: github.ref == 'refs/heads/main'

    steps:
      # Run package update
      - name: Run package update
        run: |
          sudo apt update
          sudo apt dist-upgrade -y

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get install -y python-is-python3 git python3-pip screen

      # Checks out a copy of your repository
      - name: Checkout code
        uses: actions/checkout@v2


      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: codebotler
          environment-file: $GITHUB_WORKSPACE/environment.yml
          python-version: 3.10
          auto-activate-base: false
      - run: |
          conda info
          conda list
          pip3 install torch torchvision torchaudio

      # - name: Install dependencies
      #   run: |
      #     cd $GITHUB_WORKSPACE
      #     echo "begin: PATH=$PATH;"
      #     conda info
      #     conda -V
      #     conda env create -f environment.yml
      #     conda activate codebotler || true
      #     echo "after conda activate codebotler: PATH=$PATH;"
      #     pip3 install torch torchvision torchaudio

      - name: Catkin make
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          cd $GITHUB_WORKSPACE/robot_interface
          catkin_make

      - name: Run robot server interface
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          source $GITHUB_WORKSPACE/robot_interface/devel/setup.bash
          screen -s bash -mdS roscore roscore
          sleep 2
          cd $GITHUB_WORKSPACE
          timeout --preserve-status 5 python3 robot_interface/src/robot_server_example.py

      - name: Run deployment interface with robot server
        shell: bash
        run: |
          source /opt/ros/noetic/setup.bash
          source $GITHUB_WORKSPACE/robot_interface/devel/setup.bash
          screen -s bash -mdS roscore roscore
          sleep 2
          cd $GITHUB_WORKSPACE
          screen -s bash -mdS robot_server python3 robot_interface/src/robot_server_example.py
          export OPENAI_API_KEY=FAKE_KEY
          timeout --preserve-status -s SIGINT 5 python3 codebotler.py --robot --ip 0.0.0.0
